CREATE DATABASE QuanLyDiemThi;
USE QuanLyDiemThi;
CREATE TABLE HocSinh (
    MaHS VARCHAR(20) PRIMARY KEY ,
    TenHS VARCHAR(50) NOT NULL ,
    NgaySinh DATETIME NOT NULL ,
    Lop VARCHAR(10) NOT NULL ,
    GT VARCHAR(20)
);

CREATE TABLE MonHoc (
    MaMH VARCHAR(20) PRIMARY KEY ,
    TenMH VARCHAR(50) NOT NULL
);

CREATE TABLE BangDiem (
    MaHS VARCHAR(20) NOT NULL ,
    MaMH VARCHAR(20) NOT NULL ,
    DiemThi INT,
    NgayKT DATETIME,
    PRIMARY KEY (MaHS, MaMH) ,
    FOREIGN KEY (MaHS) REFERENCES HocSinh(MaHS),
    FOREIGN KEY (MaMH) REFERENCES MonHoc(MaMH)
);

CREATE TABLE GiaoVien (
    MaGV VARCHAR(20) PRIMARY KEY ,
    TenGV VARCHAR(50),
    SDT VARCHAR(10)
);

ALTER TABLE MonHoc ADD MaGV VARCHAR(20);
ALTER TABLE MonHoc ADD CONSTRAINT FK_MaGV FOREIGN KEY (MaGV) REFERENCES GiaoVien(MaGV);

SELECT * FROM MonHoc;
SELECT * FROM GiaoVien;